version: "3.9"

services:
  database:
    ports:
      - 8005:5432
    image: postgres:14
    networks:
      - simtix
    volumes:
      - db:/var/lib/postgresql/data
    env_file: .env
  simtix-payment:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    env_file: .env

networks:
  simtix:
    external: true

volumes:
  db: