version: "3.8"

services:
  database:
    ports:
      - 8005:5432
    image: postgres:14
    networks:
      - simtix-payment
    volumes:
      - db:/var/lib/postgresql/data
    env_file: .env

networks:
  simtix-payment:

volumes:
  db: